version: '3'

services:
  frontend:
    build: ./frontend  # Path to the frontend directory
    ports:
      - "80:80"  # Exposes frontend on port 80

  backend:
    build: ./backend  # Path to the backend directory
    ports:
      - "5000:5000"  # Exposes backend on port 5000
    environment:
      AWS_ACCESS_KEY: "AKIAUMGOBIDFCZMYSFTF"  # Replace with your actual AWS keys or use environment variables
      AWS_SECRET_KEY: "HqUWa2UdRTGNPeYUCR9N3xCgNcrRryheJLTODah+"
      AWS_REGION: "ap-south-1"
      S3_BUCKET: "myviddev"
